### ISSUE TITLE
Automatically close stale PRs and branches

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-baseline#125]
Create a reusable workflow in this repository that uses [this action](https://github.com/actions/stale) to automatically close stale PRs and branches.

Call this workflow in all module repositories.

**Comment by hknutsen** [comment]
Should be implemented for https://github.com/equinor/terraform-module-template as well.

**Comment by helenakallekleiv** [comment]
> Should be implemented for https://github.com/equinor/terraform-module-template as well.

PR created here: https://github.com/equinor/terraform-module-template/pull/11
