### ISSUE TITLE
Do not create a random password if a admin_password is provided to the VM module

### ISSUE THREAD

**Issue by stiross79** [equinor/terraform-baseline#135]
### Module Name

vm

### Description

Only create the random password resource if an admin_password has not been provided.

### Example Terraform Configuration

```terraform
resource "random_password" "this" {
  count       = var.admin_password != null ? 1 : 0
...
}
```

**Comment by hknutsen** [comment]
Might not be possible, see #119. Depends on how your custom admin password is generated though.

**Comment by stiross79** [comment]
> Might not be possible, see #119. Depends on how your custom admin password is generated though.

In our case, we already have our VMs with a random password stored in the state. With the current config, we will have two `random_password` resources, but only one that will be used.

**Comment by stiross79** [comment]
@hknutsen  What value will not be known during the planning?

**Comment by hknutsen** [comment]
Consider the following example configuration:

```terraform
resource "random_password" "custom" {
  length      = 128
  lower       = true
  upper       = true
  numeric     = true
  special     = true
  min_lower   = 1
  min_upper   = 1
  min_numeric = 1
  min_special = 1
}

resource "random_password" "default" {
  count = random_password.custom.result == null ? 1 : 0

  length      = 16
  lower       = true
  upper       = true
  numeric     = true
  special     = true
  min_lower   = 1
  min_upper   = 1
  min_numeric = 1
  min_special = 1
}
```

Assumptions:
- `random_password.default` is the password generated by the `vm` module.
- `random_password.custom` is the custom password you pass to the `vm` module.

Running `terraform plan` throws the following error:

```console
$ terraform plan
╷
│ Error: Invalid count argument
│
│   on main.tf line 14, in resource "random_password" "default":
│   14:   count = random_password.custom.result == null ? 1 : 0
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources   
│ that the count depends on.
╵
```

This is because the `random_password` resource generates a password. Generated values are not known until the after the resource has been created by `terraform apply`.

Note that the error message specifies that you can use `terraform apply -target=...` to work around this, however it seems like a flaky workaround to me.

**Comment by stiross79** [comment]
I would agree if you rely on the output result from another resource within the module for `count`. But in our case, we are referring to a variable that is either supplied by its consumer or defaults to `null`.

**Comment by hknutsen** [comment]
But if the provided value of that variable comes from a resource, you can run into the same problem.

Basically, the suggested implementation would completely remove the possibility of providing a custom password generated by Terraform.

**Comment by hknutsen** [comment]
Leaving the issue open for a little longer though, in case we come up with a solution 🙌

**Comment by hknutsen** [comment]
Might be worth taking a new look at this once Terraform 1.9 has been released:

> The experimental "deferred actions" feature, enabled by passing the `-allow-deferral` option to `terraform plan`, permits `count` and `for_each` arguments in `module`, `resource`, and `data` blocks to have unknown values and allows providers to react more flexibly to unknown values. This experiment is under active development, and so it's not yet useful to participate in this experiment.

From [changelog](https://github.com/hashicorp/terraform/blob/3a1c70d4fa812acd41e3ddffbf8bc27631ed6aa9/CHANGELOG.md#190-unreleased).

**Comment by helenakallekleiv** [comment]
> Might be worth taking a new look at this once Terraform 1.9 has been released:
> 
> > The experimental "deferred actions" feature, enabled by passing the `-allow-deferral` option to `terraform plan`, permits `count` and `for_each` arguments in `module`, `resource`, and `data` blocks to have unknown values and allows providers to react more flexibly to unknown values. This experiment is under active development, and so it's not yet useful to participate in this experiment.
> 
> From [changelog](https://github.com/hashicorp/terraform/blob/3a1c70d4fa812acd41e3ddffbf8bc27631ed6aa9/CHANGELOG.md#190-unreleased).

As of today, the "deferred actions" feature is still labed as an experiment in the [alpha pre-release of Terraform 1.10](https://github.com/hashicorp/terraform/releases/tag/v1.10.0-alpha20240926), so we might have to wait a while for it. 

I think we can close this issue for now and rather keep an eye on the changelog for when the "deferred actions" feature moves out from the experimentation stage. 

Any other thoughts @equinor/terraform-baseline-maintainers?
