### ISSUE TITLE
chore: add code owners

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-baseline#15]
Add code owners to all module repos (including template?)

Rerun `scripts/configure_repo.sh` to ensure repo settings are set to enforce PR approval from code owners.

**Comment by helenakallekleiv** [comment]
@hknutsen All module repos (exept template) are now updated with code owners. 

What is the status on rerunning `scripts/configure_repo.sh`?

**Comment by hknutsen** [comment]
@helenakallekleiv 

- You could try running the configuration script for all repos, but you might lack the required permissions.
- I wouldn't add code owners to the template, since the template is meant to be generic.

**Comment by helenakallekleiv** [comment]
@hknutsen Allright, should we leave it for later then?

**Comment by hknutsen** [comment]
@hknutsen Create an issue and one of the admins for the repos could do the configuration 😄
