### ISSUE TITLE
function app module sticky_settings

### ISSUE THREAD

**Issue by sebastianlolv** [equinor/terraform-baseline#183]
Function App has an argument for sticky_settings which are names for app_settings and connections_strings under Environment Variables tab in the Function App Resource that will not change if someone decides to Swap Deployment Slots.

The issue is that if these are set manually in Azure, the pipeline will delete them as they aren't in the TF State. 
Example of some Azure sticky_settings app_settings names.
![image](https://github.com/user-attachments/assets/1d1884e0-d766-4a16-9a20-b97f39f65b35)

Link to arguments in Terraform Registry: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app#app_setting_names

Do we make the module ignore these, create a variable or do nothing?

**Comment by hknutsen** [comment]
I propose the following new variables:

```terraform
variable "sticky_settings_app_setting_names" {
  description = "A list of names of app settings that this Function App will not swap between slots when a swap operation is triggered."
  type        = list(string)
  default     = []
}

variable "sticky_settings_connection_string_names" {
  description = "A list of names of connection strings that this Function App will not swap between slots when a swap operation is triggered."
  type        = list(string)
  default     = []
}
