### ISSUE TITLE
Add input auto_pause_delay_in_minutes to terraform-azurerm-sql/modules/database

### ISSUE THREAD

**Issue by chbul** [equinor/terraform-baseline#197]
### Module Name

Database submodule

### Description

- Add input: `auto_pause_delay_in_minutes`
- Ref : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database#auto_pause_delay_in_minutes-1

### Example Terraform Configuration

```terraform
variable "sql_database_auto_pause_delay_in_minutes" {
  description = "(Optional) Time in minutes after which database is automatically paused. A value of -1 means that automatic pause is disabled. This property is only settable for Serverless databases."
  type        = number
  default     = 0
}
```

**Comment by hknutsen** [comment]
I ran `terraform state show` locally, targeting a database created using this module, and can confirm that the default value of `auto_pause_delay_in_minutes` is `0`.
