### ISSUE TITLE
Publish modules to Terraform Registry

### ISSUE THREAD

**Issue by nemanja-drobac** [equinor/terraform-baseline#36]
# Description

We need to see if we can upload Terraform modules to Public Registry.
The idea is to have one common place to store all modules we develop.

**Comment by hknutsen** [comment]
According to Terraform docs, Terraform Registry wants the following accesses for the user publishing the module:

- Read org and team membership, read org projects
- Access user email addresses (read-only)
- Write repository hooks

**Comment by kov117** [comment]
should we close this issue now that we have published our modules to the registry @hknutsen and @nemanja-drobac ? 

Ref: https://registry.terraform.io/search/modules?namespace=equinor&provider=azure

**Comment by hknutsen** [comment]
Yup 🙂 Closing.
