### ISSUE TITLE
Create consumption module

### ISSUE THREAD

**Issue by nemanja-drobac** [equinor/terraform-baseline#38]
> **Warning**
> Avoid pasting images in issues!

## Purpose

New reusable terraform module for azure budgets.

## Detailed description

The Idea is to create a reusable terraform module for `azurerm` provider that will simplify creating `subscription` or `resourcegroup` budgets.

Following links refers to current standard from terraform docs `azurerm` provider:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/consumption_budget_subscription
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/consumption_budget_resource_group

## Tasks

- [ ] Create reusable module with name `terraform-azurerm-budget`

## Affected Items

- [x] None

**Comment by hknutsen** [comment]
Suggestions:
- Create module `consumption` for the `Microsoft.Consumption` resource provider instead of creating a module `budget`. This would allow us to easily expand the module in the future if other features are added to this provider.

**Comment by nemanja-drobac** [comment]
@stiross79 
Do you have anything you could contribute with regarding creation of terraform module for Azure budgets?

**Comment by hknutsen** [comment]
Imo. no need to create a module for something that we aren't using yet.

If someone already has a `consumption` module, we can consider adding it to the Baseline library.

**Comment by stiross79** [comment]
> @stiross79 Do you have anything you could contribute with regarding creation of terraform module for Azure budgets?

We do not create budgets for our project. So I do not have much experience with this, unfortunately.

**Comment by nemanja-drobac** [comment]
@hknutsen @stiross79 

Thank you for quick response here. I am then closing this issue for now. We can create a new issue when we have plans to do something about this in future or reopen this one.
