### ISSUE TITLE
chore: enforce PR approval from code owners

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-baseline#41]
Ensure repository settings are set to enforce PR approval from code owners, by rerunning `scripts/configure_repo.sh` as shown in the [usage example](https://github.com/equinor/terraform-baseline/tree/main/scripts#usage), in all module repositories. [Module library](https://github.com/equinor/terraform-baseline#module-library)

This action requires admin/owner role in the given repo.

```bash
cd scripts/
./configure_repo.sh acr
./configure_repo.sh app-config
./configure_repo.sh app-insights
./configure_repo.sh app-service
./configure_repo.sh automation
./configure_repo.sh container
./configure_repo.sh databricks
./configure_repo.sh event-grid
./configure_repo.sh function-app
./configure_repo.sh grafana
./configure_repo.sh identity
./configure_repo.sh key-vault
./configure_repo.sh log-analytics
./configure_repo.sh network
./configure_repo.sh postgres
./configure_repo.sh sql
./configure_repo.sh storage
./configure_repo.sh web-app
```

**Comment by hknutsen** [comment]
I've executed the code snippet to configure all repos ✅

**Comment by helenakallekleiv** [comment]
Nice, then I'll close this issue 👍🏼
