### ISSUE TITLE
Disable metrics by default

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-baseline#44]
By default, we want to only collect audit logs.

Go through all modules and make sure metrics are disabled by default.

Also consider adding a new variable to enable metrics if needed.

**Comment by helenakallekleiv** [comment]
Modules where metrics are enabled:
- [ ] App Config
- [ ] Function App
- [ ] Key Vault
- [ ] Log Analytics
- [ ] Service Bus
- [ ] Web App

**Comment by kov117** [comment]
The mentioned modules have now have metrics disabled by default, and have been made into a variable for easier enabling if needed. Any comments before we can close this isssue @equinor/terraform-baseline ?

**Comment by helenakallekleiv** [comment]
@kov117 Any more modules that could have this implemented?

**Comment by kov117** [comment]
there were quite a few, i will include them to the to the list and continue the work

**Comment by kov117** [comment]
And with that all the modules have now metrics disabled by default, except for SQL but it has its reasons [Ref](https://github.com/equinor/terraform-azurerm-sql/pull/130). and with that i will close this issue 👋🏽.
