### ISSUE TITLE
Clarify when to create submodules

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-baseline#46]
We've created `database` as a submodule of `sql`, and `runbook` as a submodule of `automation`. These make sense to me, as a database requires a SQL server to run on, and a runbook requires an automation account to run on.

We've also created `nsg`, `nat`, and `public-ip` as submodules of `network`, however none of these submodules actually require a virtual network to be created. Thus I'd argue it makes sense to move these into their own standalone modules.

Thoughts?

Any ideas for how we'd phrase this in our best practices?

**Comment by helenakallekleiv** [comment]
The criteria we have per now for creating sub-modules are:
```txt
There should be a one-to-one mapping between module calls and visible resources in Azure.
...
Each module call corresponds to a single visible resource in the Azure portal:
...
```
And from my understanding, for a resource to be in it's own sub-module it needs to be visible as a standalone resource, but is a child resource and requires the parent resource. E.g. `app_insights` and `web_test`, where the `web_test` sub-module requires the `app_insights` module to be created. 

We could perhaps phrase it something like this? ☝🏼

**Comment by sebastianlolv** [comment]
Sure, it makes sense, but isn't it possible to just call the nested modules by themselves with the //? Maybe not best practice. It's just going to be a lot of modules then to keep up with.

**Comment by hknutsen** [comment]
> Sure, it makes sense, but isn't it possible to just call the nested modules by themselves with the //? Maybe not best practice. It's just going to be a lot of modules then to keep up with.

Yes that's how we do it today with the `//`,.

However if `network` contains the main module + 4 submodules (that don't even have anything to do with the virtual network module), then making a breaking change will affect 5 modules in total.

**Comment by hknutsen** [comment]
How about this phrasing?

```markdown
If a resource is a child of another resource:
- The parent resource should be configured as a module
- The child resource should be configure as a submodule

E.g., a SQL database resource is a child of the SQL server resource (i.e. a SQL database cannot exist without a SQL server):
- The SQL server resource should be configured as a module `sql`
- The SQL database resource should be configured as a submodule `sql//modules/database`
```

**Comment by helenakallekleiv** [comment]
> How about this phrasing?
> 
> ```
> If a resource is a child of another resource:
> - The parent resource should be configured as a module
> - The child resource should be configured as a submodule
> 
> For example, the SQL database resource is a child of the SQL server resource (a SQL database cannot exist without a SQL server):
> - The SQL server resource should be configured as a module `sql`
> - The SQL database resource should be configured as a submodule `sql//modules/database`
> ```

What if we add some description specifying that we configure sub-modules only if it contains resources that should always be created? Similarly to the Web Test sub-module in the App Insights module: https://github.com/equinor/terraform-azurerm-app-insights/issues/21

```markdown
If a resource is a child of another resource and should always be created:
- The parent resource should be configured as a module
- The child resource should be configured as a submodule

For example, the SQL database resource is a child of the SQL server resource (a SQL database cannot exist without a SQL server):
- The SQL server resource should be configured as a module `sql`
- The SQL database resource should be configured as a submodule `sql//modules/database`

Unnecessary creation of a sub-module: 
- For example, the Web Test resource is a child of the App Insights resource and is visible as an individual resource in Azure (App Insights can exist without Web Tests).
```

**Comment by helenakallekleiv** [comment]
> > How about this phrasing?
> > ```
> > If a resource is a child of another resource:
> > - The parent resource should be configured as a module
> > - The child resource should be configured as a submodule
> > 
> > For example, the SQL database resource is a child of the SQL server resource (a SQL database cannot exist without a SQL server):
> > - The SQL server resource should be configured as a module `sql`
> > - The SQL database resource should be configured as a submodule `sql//modules/database`
> > ```
> 
> What if we add some description specifying that we configure sub-modules only if it contains resources that should always be created? Similarly to the Web Test sub-module in the App Insights module: https://github.com/equinor/terraform-azurerm-app-insights/issues/21
> 
> If a resource is a child of another resource and should always be created:
> - The parent resource should be configured as a module
> - The child resource should be configured as a submodule
> 
> For example, the SQL database resource is a child of the SQL server resource (a SQL database cannot exist without a SQL server):
> - The SQL server resource should be configured as a module `sql`
> - The SQL database resource should be configured as a submodule `sql//modules/database`
> 
> Unnecessary creation of a sub-module: 
> - For example, the Web Test resource is a child of the App Insights resource and is visible as an individual resource in Azure (App Insights can exist without Web Tests).

@equinor/terraform-baseline-maintainers We should revisit this and add to Baseline documentation.

**Comment by ErlendT** [comment]
@helenakallekleiv Approved description in baseline meeting
