### ISSUE TITLE
Clarify default audit log categories

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-baseline#54]
An overview of diagnostic settings audit log categories and metrics, availiable for the resources created by modules. 
We want to narrow the scope of the modules to enforce audit logging.

Some resources have default audit categories in Azure Portal, but not all. 
Compare availiable categories in Azure and `SetByPolicy`, specifically audit categories.

 **Note:**
 - Some categories for logs and metrics are resource specific, e.g. wording and format of the category name may vary, depending on the resource.
 - Some categories cost to export, see this [overview](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/resource-logs-categories#costs). Be mindful of this when enabling categories by default.

### Microsoft Docs: Supported log categories by module

| Module        | Type                                           |
| ------------- | ---------------------------------------------- |
| ACR           | [Microsoft.ContainerRegistry/registries](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-containerregistry-registries-logs) |
| App Config    | [Microsoft.AppConfiguration/configurationStores](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-appconfiguration-configurationstores-logs) |
| App Insights  | [Microsoft.Insights/components](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-insights-components-logs) |
| App Service   | [Microsoft.Web/sites](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-web-sites-logs) |
| Automation    | [Microsoft.Automation/automationAccounts](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-automation-automationaccounts-logs) |
| ACI           | None | 
| Databricks    | [Microsoft.Databricks/workspaces](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-databricks-workspaces-logs) |
| Event Grid    | [Microsoft.EventGrid/systemTopics](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-eventgrid-systemtopics-logs) |
| Function App  | [Microsoft.Web/sites](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-web-sites-logs) |
| Grafana       | [Microsoft.Dashboard/grafana](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-dashboard-grafana-logs) |
| Identity      | None |
| Key Vault     | [Microsoft.KeyVault/vaults](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-keyvault-vaults-logs) |
| Log Analytics | [Microsoft.OperationalInsights/workspaces](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-operationalinsights-workspaces-logs) |
| Network       | None |
| Postgres      | [Microsoft.DBforPostgreSQL/servers](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-dbforpostgresql-servers-logs) |
| SQL           | [Microsoft.Sql/servers/databases](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-sql-servers-databases-logs) |
| Storage       | [Microsoft.Storage/storageAccounts/**](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-storage-storageaccounts-blobservices-logs) |
| Web App       | [Microsoft.Web/sites](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-web-sites-logs) |

### Log categories by default: `SetByPolicy` versus Modules

| Module | Default categories in `SetByPolicy` | Default categories in modules |
| ------ | --------------- | -------------- |
| ACR    | `ContainerRegistryLoginEvents` <br> `ContainerRegistryRepositoryEvents` | `ContainerRegistryLoginEvents` <br> `ContainerRegistryRepositoryEvents` |
| App Config | `Audit` <br> `HttpRequest` | `Audit` <br> -|
| App Insights | `AppEvents` <br> `AppRequests` <br> `AppSystemEvents` | None |
| App Service | `AppServiceAuditLogs` <br> `AppServiceIPSecAuditLogs` | None |
| Automation | `AuditEvent` <br> `JobLogs` <br> `JobStreams` <br> `DscNodeStatus` | `AuditEvent` <br> - <br> - <br> - |
| ACI | None | None |
| Databricks | `accounts` <br> `clusters` <br> - <br> `instancePools` <br> - <br> - <br> `secrets` <br> `sqlPermissions` <br> `ssh` <br> - <br> `genie` <br> `gitCredentials` | `accounts` <br> `clusters` <br> `dbfs` <br> `instancePools` <br> `jobs` <br> `notebook` <br> `secrets` <br> `sqlPermissions` <br> `ssh` <br> `workspace` <br> - <br> - |
| Event Grid | `DeliveryFailures` | `DeliveryFailures` |
| Function App | `FunctionAppLogs` | `FunctionAppLogs` |
| Grafana | `GrafanaLoginEvents` | `GrafanaLoginEvents` |
| Identity | None | None |
| Key Vault | `AuditEvent` <br> `AzurePolicyEvaluationDetails` | `AuditEvent` <br> - |
| Log Analytics | `Audit` | `Audit` |
| Network | None | None |
| Postgres | `PostgreSQLLogs` | `PostgreSQLLogs` |
| SQL | `Errors` <br> - | - <br> `SQLSecurityAuditEvents` |
| Storage | `StorageRead` <br> `StorageWrite` <br> `StorageDelete` | `StorageRead` <br> `StorageWrite` <br> `StorageDelete` |
| Web App | - <br> - <br> - <br> `AppServiceAuditLogs` <br> `AppServiceIPSecAuditLogs` <br> - | `AppServiceHTTPLogs` <br> `AppServiceConsoleLogs` <br> `AppServiceAppLogs` <br> `AppServiceAuditLogs` <br> `AppServiceIPSecAuditLogs` <br> `AppServicePlatformLogs` |

### Metrics by default: `SetByPolicy` versus Modules

| Module                | `setByPolicy` | Modules  |
| --------------------- | ------------- | -------- |
| ACR (Archive)         | None          | Enabled  |
| App Config            | None          | Enabled  |
| App Insights          | None          | None     |
| App Service (Archive) | None          | None     |
| Automation            | None          | Disabled |
| ACI (Archive)         | None          | None     |
| Databricks            | None          | None     |
| Event Grid            | None          | Disabled |
| Function App          | None          | Enabled  |
| Grafana               | None          | Disabled |
| Identity              | None          | None     |
| Key Vault             | None          | Enabled  |
| Log Analytics         | None          | Enabled  |
| Network               | None          | None     |
| Postgres              | None          | Disabled |
| Service Bus           | None          | Enabled  |
| SQL                   | None          | Disabled |
| Storage               | None          | Disabled |
| Web App               | None          | Enabled  |

**Comment by helenakallekleiv** [comment]
Maybe, instead of a metrics-table we include a note on that by default we only want to collects audit logs, therefore all metrics are disabled?

**Comment by hknutsen** [comment]
What would be the benefit of documenting available audit logs in this repo, rather than just enabling recommended logs in the module themselves and letting users enable additional logs when needed?

**Comment by helenakallekleiv** [comment]
> What would be the benefit of documenting available audit logs in this repo, rather than just enabling recommended logs in the module themselves and letting users enable additional logs when needed?

This was relevant for how we implemented the log and metric catorgies before, but now it makes more sense to let the user enable additional logs yes. The documented categories here was to specify which audit logs was available for each resource, and also compare them to the defaults in the `setByPolicy` diagnostic setting as well as by default in Azure. 

We can go ahead and close this issue 👍

**Comment by hknutsen** [comment]
Stale.
