### ISSUE TITLE
Consider custom labels for public repos

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-baseline#96]
Consider `terraform-baseline` as source repository for general custom labels, in public repo context.

- https://github.com/equinor/terraform-baseline/labels

**Comment by chbul** [comment]
Great suggestion! Do you think we should add this to the documentation?

**Comment by helenakallekleiv** [comment]
> Great suggestion! Do you think we should add this to the documentation?

First we need to consider what labels should be included I think, and have a discussion. Please include suggestions for labels if you have some ideas! 🎉

**Comment by hknutsen** [comment]
No longer relevant now that Issues are tracked centrally in this repo.
