### ISSUE TITLE
Migrate to native Terraform test functionality

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-baseline#98]
Terraform v1.7 introduced a native Terraform test functionality. Today we use Go to test the modules, but we should consider migrating to the native functionality for all modules.

- https://developer.hashicorp.com/terraform/language/tests
- https://developer.hashicorp.com/terraform/tutorials/configuration-language/test

**Comment by kov117** [comment]
@helenakallekleiv updates ?

**Comment by helenakallekleiv** [comment]
Update on which modules is currently ongoing migration:
- Storage: https://github.com/equinor/terraform-azurerm-storage/pull/204
- SQL: https://github.com/equinor/terraform-azurerm-sql/pull/135
- Service Bus: https://github.com/equinor/terraform-azurerm-service-bus/pull/40

**Comment by helenakallekleiv** [comment]
We will use the Storage module as the "base" for how the tests will be structured. 

The current suggestion is that we split the tests into unit tests (plan) and integration/"end 2 end" tests (apply)

**Comment by helenakallekleiv** [comment]
This issue is a duplicate of #143. Closing.
